//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        public int id { get; set; }
        public Nullable<int> id_libros { get; set; }
        public Nullable<int> id_socios { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Libros Libros { get; set; }
        public virtual Socios Socios { get; set; }

        public bool GuardarAlquiler(Alquiler alq)
        {
            bool resultado = false;
            AlquilerLibrosEntities db = new AlquilerLibrosEntities();
            db.Alquiler.Add(alq);
            if (db.SaveChanges() == 1)
                resultado = true;

            return resultado;
        }
    }
}
